steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage', './AuthBoilerplate']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage']