steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'AuthBoilerplate/Dockerfile', '-t', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/gc-docker/myimage', '.']
    secretEnv: ['ConnectionStrings__AuthConnectionString']
    availableSecrets:
        secretManager:
          - versionName: projects/${PROJECT_ID}/secrets/DB_URL/versions/latest
            env: ConnectionStrings__AuthConnectionString

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/gc-docker/myimage']